#%RAML 1.0 DataType
type: object
properties:
  Id:
    type: string
    example: 800Qy00000GEIwjIAH
  AccountId:
    type: string
    example: 001Qy00000OJydlIAD
  ExternalId__c:
    type: string
    example: 5eb87cdbffd86e000604b32d
  SuccessStatus__c:
    type: string
    example: success
  DateCreation__c:
    type: date-only
    example: 2024-07-12
  Details__c:
    type: string
    example: Hello
  RocketName__c:
    type: string
    example: Rocket
  NameSalesforce__c:
    type: string
    example: Name
  Status:
    type: string
    example: Draft
  StartDate:
    type: date-only
    example: 2023-06-28
  ContractTerm:
    type: integer
    example: 1