#%RAML 1.0 DataType

displayName: Launch
description: Defines the Launch data type

type: object
properties:
  fairings:
    type: null
  links:
    type: object
    properties:
      patch:
        type: object
        properties:
          small:
            type: string
          large:
            type: string
      reddit:
        type: object
        properties:
          campaign:
            type: string
          launch:
            type: string
          media:
            type: string
          recovery:
            type: string
      flickr:
        type: object
        properties:
          small:
            type: array
            items:
              type: string
          original:
            type: array
            items:
              type: string
      presskit:
        type: string
      webcast:
        type: string
      youtube_id:
        type: string
      article:
        type: string
      wikipedia:
        type: string
  static_fire_date_utc:
    type: datetime
  static_fire_date_unix:
    type: integer
  tdb:
    type: boolean
  net:
    type: boolean
  window:
    type: integer
  rocket:
    type: string
  success:
    type: boolean
  failures:
    type: array
    items:
      type: string
  details:
    type: string
  crew:
    type: array
    items:
      type: string
  ships:
    type: array
    items:
      type: string
  capsules:
    type: array
    items:
      type: string
  payloads:
    type: array
    items:
      type: string
  launchpad:
    type: string
  auto_update:
    type: boolean
  flight_number:
    type: integer
  name:
    type: string
  date_utc:
    type: datetime
  date_unix:
    type: integer
  date_local:
    type: datetime
  date_precision:
    type: string
    enum: [year, half, quarter, month, day, hour]
  upcoming:
    type: boolean
  cores:
    type: array
    items:
      type: object
      properties:
        core:
          type: string
        flight:
          type: integer
        gridfins:
          type: boolean
        legs:
          type: boolean
        reused:
          type: boolean
        landing_attempt:
          type: boolean
        landing_success:
          type: boolean
        landing_type:
          type: string
        landpad: 
          type: string
    
  id:
    type: string